### ISSUE TITLE
Online demo / REPL?

### ISSUE THREAD

**Issue by mathiasbynens** [slevithan/babel-plugin-transform-regex#1]
The Babel REPL supports loading plugins, so it should be possible to add a demo link to the README that has this particular transform pre-enabled. Something like:

```
https://babeljs.io/repl#?externalPlugins=slevithan/babel-plugin-transform-regex@0.1.0&code_lz=MYewdgzgLgBATgUxgXngg5ggHgAwGYgg4DcAUKaJCADYIB01I6AFAOQCGARsDASDJ3ZxehAewBerOgFt2UYAAtmiAJQriQA
```

However, I just tried loading the plugin via the REPL UI and it failed to load.

**Comment by slevithan** [comment]
Hm, it looks like some other plugins also don't work in the Babel REPL.

When trying to load this plugin, the REPL tries to import from <https://packd.liuxingbaoyu.xyz/babel-plugin-transform-regex@0.1.0>, but that page returns error ``"package has no entry file; please specify a `module` key in your `package.json`."``

I tried adding the `module` field, but that didn't work. It led to the packd endpoint linked above returning error `"Can't walk dependency graph: Cannot find module 'regex' from '<...>' required by <...>"`. I also tried exporting `babel-plugin-transform-regex` as CommonJS to see if there was any way that would make the Babel REPL work, but predicably no since the `regex` package it requires is ESM.

I've now undone most of my changes and I'm giving up for now, since I suspect I might not be able to make it work without additionally providing a CommonJS build of `regex`. I'm open to doing that if someone submits a PR (since I'm not very familiar with build systems) for dual CommonJS and ESM. But even better would be if someone figures out how to make `babel-plugin-transform-regex` work within the Babel REPL without changing `regex`.

**Comment by slevithan** [comment]
Adding the `module` field didn't work. It led to the packd endpoint (linked above) returning error `"Can't walk dependency graph: Cannot find module 'regex' from '<...>' required by <...>"`. I then tried exporting `babel-plugin-transform-regex` as CommonJS but predicably that didn't work since the `regex` package it requires is ESM-only. I noticed that some other Babel plugins also can't be imported in the Babel REPL. I suspect the Babel REPL, or packd that it relies on for importing plugins, requires CommonJS modules. If that's wrong, I'd love to learn how to fix it.

I've undone most of my changes and am giving up for now, since I suspect I can't make it work without additionally providing a CommonJS build of `regex`. I'm open to doing that if someone submits a PR (since I'm not very familiar with build systems). Even better would be if someone can figure out how to make `babel-plugin-transform-regex` work within the Babel REPL without changing `regex`. (Perhaps there are other good REPL options where it already works?)

**Comment by slevithan** [comment]
@mathiasbynens I've added my own very basic REPL, so you can now [try it out here](https://slevithan.github.io/babel-plugin-transform-regex/demo/). I've also added support for interpolation of inline strings, numbers, regexes, and partials.

**Comment by slevithan** [comment]
I'm going to close this since an online demo/REPL is now available, but I'd love to also make this work with the official Babel REPL. So anyone seeing this with thoughts on how to enable that, feel free to open a new issue or PR!
